// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenetv2_block_depthwise_conv (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_stream_dout,
        input_stream_empty_n,
        input_stream_read,
        input_stream_num_data_valid,
        input_stream_fifo_cap,
        internal_fifo_din,
        internal_fifo_full_n,
        internal_fifo_write,
        internal_fifo_num_data_valid,
        internal_fifo_fifo_cap,
        dw_weights_address0,
        dw_weights_ce0,
        dw_weights_q0,
        dw_weights_address1,
        dw_weights_ce1,
        dw_weights_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] input_stream_dout;
input   input_stream_empty_n;
output   input_stream_read;
input  [2:0] input_stream_num_data_valid;
input  [2:0] input_stream_fifo_cap;
output  [15:0] internal_fifo_din;
input   internal_fifo_full_n;
output   internal_fifo_write;
input  [31:0] internal_fifo_num_data_valid;
input  [31:0] internal_fifo_fifo_cap;
output  [8:0] dw_weights_address0;
output   dw_weights_ce0;
input  [15:0] dw_weights_q0;
output  [8:0] dw_weights_address1;
output   dw_weights_ce1;
input  [15:0] dw_weights_q1;

reg ap_idle;
reg input_stream_read;
reg internal_fifo_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln27_fu_812_p2;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_stream_blk_n;
reg    ap_done_reg;
wire    ap_block_pp0_stage0_grp1;
reg    internal_fifo_blk_n;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_grp2;
reg   [0:0] and_ln48_reg_1315;
reg   [0:0] and_ln48_reg_1315_pp0_iter2_reg;
reg    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
reg    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] first_iter_1_mid2_fu_446_p3;
reg   [0:0] first_iter_1_mid2_reg_1266;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [0:0] first_iter_0_fu_462_p2;
reg   [0:0] first_iter_0_reg_1270;
wire   [8:0] empty_31_fu_495_p1;
reg   [8:0] empty_31_reg_1274;
reg   [8:0] dw_weights_addr_reg_1284;
reg  signed [15:0] input_stream_read_reg_1299;
reg  signed [15:0] input_stream_read_reg_1299_pp0_iter1_reg;
reg   [5:0] line_buffer_addr_reg_1305;
wire   [0:0] and_ln48_fu_559_p2;
reg   [0:0] and_ln48_reg_1315_pp0_iter1_reg;
wire   [0:0] first_iter_1_fu_585_p2;
reg   [0:0] first_iter_1_reg_1319;
wire   [0:0] icmp_ln29_fu_591_p2;
reg   [0:0] icmp_ln29_reg_1324;
wire   [0:0] icmp_ln28_fu_597_p2;
reg   [0:0] icmp_ln28_reg_1329;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg  signed [15:0] line_buffer_load_reg_1339;
reg  signed [15:0] line_buffer_1_load_reg_1345;
reg  signed [15:0] p_0_0_0858980_load_reg_1351;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg    ap_block_pp0_stage2_subdone;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage4_11001;
reg   [0:0] icmp_ln27_reg_1416;
reg   [0:0] icmp_ln27_reg_1416_pp0_iter1_reg;
reg    ap_block_state13_pp0_stage2_iter2_grp2;
wire   [15:0] line_buffer_q0;
wire   [5:0] line_buffer_1_address0;
wire   [15:0] line_buffer_1_q0;
reg   [0:0] ap_phi_mux_icmp_ln2884_phi_fu_316_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_icmp_ln2983_phi_fu_326_p4;
reg   [0:0] ap_phi_mux_first_iter_182_phi_fu_336_p4;
wire   [63:0] p_cast88_fu_490_p1;
wire   [63:0] p_cast89_fu_505_p1;
wire   [63:0] p_cast90_fu_516_p1;
wire   [63:0] zext_ln29_fu_537_p1;
wire   [63:0] p_cast91_fu_628_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] p_cast92_fu_651_p1;
wire    ap_block_pp0_stage2_grp0;
wire   [63:0] p_cast93_fu_661_p1;
wire   [63:0] p_cast94_fu_696_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] p_cast95_fu_706_p1;
wire   [63:0] p_cast96_fu_739_p1;
wire    ap_block_pp0_stage4;
reg   [16:0] indvar_flatten7863_fu_104;
wire   [16:0] add_ln27_1_fu_744_p2;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg_iter0;
reg   [5:0] ch64_fu_108;
wire   [5:0] ch_fu_412_p3;
reg   [5:0] ap_sig_allocacmp_ch64_load;
reg   [11:0] indvar_flatten65_fu_112;
wire   [11:0] select_ln28_1_fu_577_p3;
reg   [11:0] ap_sig_allocacmp_indvar_flatten65_load;
reg   [5:0] r66_fu_116;
wire   [5:0] r_fu_454_p3;
reg   [5:0] ap_sig_allocacmp_r66_load;
reg   [5:0] c76_fu_120;
wire   [5:0] c_fu_565_p2;
reg   [5:0] ap_sig_allocacmp_c76_load;
reg   [15:0] p_0_0_083_2_19277_fu_124;
reg   [15:0] p_0_0_083_1_19079_fu_128;
reg   [15:0] p_0_0_083_1138881_fu_132;
reg  signed [15:0] dw_weights_load3467_fu_136;
reg  signed [15:0] dw_weights_load_13068_fu_140;
reg  signed [15:0] dw_weights_load_22669_fu_144;
reg  signed [15:0] dw_weights_load_32270_fu_148;
reg  signed [15:0] dw_weights_load_41871_fu_152;
wire    ap_block_pp0_stage0_grp0;
reg  signed [15:0] dw_weights_load_51472_fu_156;
reg  signed [15:0] dw_weights_load_61073_fu_160;
reg  signed [15:0] dw_weights_load_7674_fu_164;
reg  signed [15:0] dw_weights_load_8275_fu_168;
reg   [15:0] empty_fu_172;
reg   [15:0] p_0_0_085_19178_fu_176;
reg   [15:0] p_0_0_0858980_fu_180;
reg    ap_block_pp0_stage2_01001_grp2;
reg    ap_block_pp0_stage2_11001_grp2;
reg    dw_weights_ce1_local;
reg   [8:0] dw_weights_address1_local;
reg    dw_weights_ce0_local;
reg   [8:0] dw_weights_address0_local;
reg    line_buffer_ce0_local;
reg   [5:0] line_buffer_address0_local;
reg    line_buffer_we0_local;
reg    line_buffer_1_ce0_local;
reg    line_buffer_1_we0_local;
wire   [0:0] xor_ln27_fu_400_p2;
wire   [5:0] add_ln27_fu_380_p2;
wire   [5:0] select_ln27_fu_386_p3;
wire   [0:0] and_ln27_fu_406_p2;
wire   [0:0] empty_29_fu_426_p2;
wire   [5:0] r_3_fu_420_p2;
wire   [0:0] first_iter_1_mid1_fu_440_p2;
wire   [0:0] or_ln27_fu_394_p2;
wire   [5:0] c_mid2_fu_432_p3;
wire   [8:0] tmp_1_fu_472_p3;
wire   [9:0] p_shl_fu_480_p1;
wire   [9:0] select_ln27_1_cast_fu_468_p1;
wire   [9:0] empty_30_fu_484_p2;
wire   [8:0] empty_32_fu_499_p2;
wire   [8:0] empty_33_fu_510_p2;
wire   [4:0] tmp_2_fu_521_p4;
wire   [4:0] tmp_3_fu_543_p4;
wire   [0:0] icmp_fu_531_p2;
wire   [0:0] icmp_ln48_fu_553_p2;
wire   [11:0] add_ln28_1_fu_571_p2;
wire   [8:0] empty_34_fu_623_p2;
wire   [8:0] empty_35_fu_646_p2;
wire   [8:0] empty_36_fu_656_p2;
wire  signed [15:0] sext_ln52_10_fu_683_p0;
wire   [8:0] empty_37_fu_691_p2;
wire   [8:0] empty_38_fu_701_p2;
wire   [8:0] empty_39_fu_734_p2;
wire  signed [15:0] sext_ln52_9_fu_780_p0;
wire   [23:0] mul_ln52_fu_784_p2;
wire   [15:0] tmp_fu_790_p4;
wire  signed [15:0] sext_ln52_12_fu_808_p0;
wire  signed [23:0] tmp_s_fu_842_p1;
wire   [23:0] grp_fu_1068_p3;
wire   [15:0] tmp_s_fu_842_p4;
wire  signed [15:0] sext_ln52_13_fu_859_p0;
wire  signed [23:0] tmp_62_fu_879_p1;
wire   [23:0] grp_fu_1077_p3;
wire   [15:0] tmp_62_fu_879_p4;
wire  signed [23:0] tmp_63_fu_909_p1;
wire   [23:0] grp_fu_1086_p3;
wire   [15:0] tmp_63_fu_909_p4;
wire  signed [15:0] sext_ln52_15_fu_926_p0;
wire  signed [23:0] tmp_64_fu_940_p1;
wire   [23:0] grp_fu_1095_p3;
wire   [15:0] tmp_64_fu_940_p4;
wire  signed [15:0] sext_ln52_16_fu_957_p0;
wire  signed [23:0] tmp_65_fu_977_p1;
wire   [23:0] grp_fu_1104_p3;
wire   [15:0] tmp_65_fu_977_p4;
wire  signed [23:0] tmp_66_fu_997_p1;
wire   [23:0] grp_fu_1113_p3;
wire   [15:0] tmp_66_fu_997_p4;
wire  signed [23:0] tmp_67_fu_1014_p1;
wire   [23:0] grp_fu_1122_p3;
wire   [15:0] tmp_67_fu_1014_p4;
wire  signed [23:0] trunc_ln_fu_1031_p1;
wire   [23:0] grp_fu_1131_p3;
wire  signed [23:0] trunc_ln2_fu_1040_p1;
wire   [15:0] trunc_ln_fu_1031_p4;
wire   [0:0] icmp_ln55_fu_1049_p2;
wire   [14:0] trunc_ln2_fu_1040_p4;
wire   [14:0] select_ln55_fu_1055_p3;
wire   [23:0] grp_fu_1068_p2;
wire   [23:0] grp_fu_1077_p2;
wire   [23:0] grp_fu_1086_p2;
wire   [23:0] grp_fu_1095_p2;
wire   [23:0] grp_fu_1104_p2;
wire   [23:0] grp_fu_1113_p2;
wire   [23:0] grp_fu_1122_p2;
wire   [23:0] grp_fu_1131_p2;
reg    grp_fu_1068_ce;
reg    grp_fu_1077_ce;
reg    grp_fu_1086_ce;
reg    grp_fu_1095_ce;
reg    grp_fu_1104_ce;
reg    grp_fu_1113_ce;
reg    grp_fu_1122_ce;
reg    grp_fu_1131_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage2;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_992;
reg    ap_condition_177;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 indvar_flatten7863_fu_104 = 17'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 = 1'b0;
#0 ch64_fu_108 = 6'd0;
#0 indvar_flatten65_fu_112 = 12'd0;
#0 r66_fu_116 = 6'd0;
#0 c76_fu_120 = 6'd0;
#0 p_0_0_083_2_19277_fu_124 = 16'd0;
#0 p_0_0_083_1_19079_fu_128 = 16'd0;
#0 p_0_0_083_1138881_fu_132 = 16'd0;
#0 dw_weights_load3467_fu_136 = 16'd0;
#0 dw_weights_load_13068_fu_140 = 16'd0;
#0 dw_weights_load_22669_fu_144 = 16'd0;
#0 dw_weights_load_32270_fu_148 = 16'd0;
#0 dw_weights_load_41871_fu_152 = 16'd0;
#0 dw_weights_load_51472_fu_156 = 16'd0;
#0 dw_weights_load_61073_fu_160 = 16'd0;
#0 dw_weights_load_7674_fu_164 = 16'd0;
#0 dw_weights_load_8275_fu_168 = 16'd0;
#0 empty_fu_172 = 16'd0;
#0 p_0_0_085_19178_fu_176 = 16'd0;
#0 p_0_0_0858980_fu_180 = 16'd0;
end

mobilenetv2_block_depthwise_conv_line_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 56 ),
    .AddressWidth( 6 ))
line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_address0_local),
    .ce0(line_buffer_ce0_local),
    .we0(line_buffer_we0_local),
    .d0(line_buffer_1_q0),
    .q0(line_buffer_q0)
);

mobilenetv2_block_depthwise_conv_line_buffer_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 56 ),
    .AddressWidth( 6 ))
line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_1_address0),
    .ce0(line_buffer_1_ce0_local),
    .we0(line_buffer_1_we0_local),
    .d0(input_stream_dout),
    .q0(line_buffer_1_q0)
);

mobilenetv2_block_mul_16s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_16s_16s_24_1_1_U4(
    .din0(sext_ln52_9_fu_780_p0),
    .din1(dw_weights_load3467_fu_136),
    .dout(mul_ln52_fu_784_p2)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln52_10_fu_683_p0),
    .din1(dw_weights_load_13068_fu_140),
    .din2(grp_fu_1068_p2),
    .ce(grp_fu_1068_ce),
    .dout(grp_fu_1068_p3)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_load_reg_1339),
    .din1(dw_weights_load_22669_fu_144),
    .din2(grp_fu_1077_p2),
    .ce(grp_fu_1077_ce),
    .dout(grp_fu_1077_p3)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln52_12_fu_808_p0),
    .din1(dw_weights_load_32270_fu_148),
    .din2(grp_fu_1086_p2),
    .ce(grp_fu_1086_ce),
    .dout(grp_fu_1086_p3)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln52_13_fu_859_p0),
    .din1(dw_weights_load_41871_fu_152),
    .din2(grp_fu_1095_p2),
    .ce(grp_fu_1095_ce),
    .dout(grp_fu_1095_p3)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(line_buffer_1_load_reg_1345),
    .din1(dw_weights_load_51472_fu_156),
    .din2(grp_fu_1104_p2),
    .ce(grp_fu_1104_ce),
    .dout(grp_fu_1104_p3)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln52_15_fu_926_p0),
    .din1(dw_weights_load_61073_fu_160),
    .din2(grp_fu_1113_p2),
    .ce(grp_fu_1113_ce),
    .dout(grp_fu_1113_p3)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln52_16_fu_957_p0),
    .din1(dw_weights_load_7674_fu_164),
    .din2(grp_fu_1122_p2),
    .ce(grp_fu_1122_ce),
    .dout(grp_fu_1122_p3)
);

mobilenetv2_block_mac_muladd_16s_16s_24ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
mac_muladd_16s_16s_24ns_24_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(input_stream_read_reg_1299_pp0_iter1_reg),
    .din1(dw_weights_load_8275_fu_168),
    .din2(grp_fu_1131_p2),
    .ce(grp_fu_1131_ce),
    .dout(grp_fu_1131_p3)
);

mobilenetv2_block_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage2)))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_177)) begin
        c76_fu_120 <= c_fu_565_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_177)) begin
    ch64_fu_108 <= ch_fu_412_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_177)) begin
    indvar_flatten65_fu_112 <= select_ln28_1_fu_577_p3;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
    indvar_flatten7863_fu_104 <= 17'd0;
end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
    indvar_flatten7863_fu_104 <= add_ln27_1_fu_744_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_177)) begin
    r66_fu_116 <= r_fu_454_p3;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln48_reg_1315 <= and_ln48_fu_559_p2;
        and_ln48_reg_1315_pp0_iter1_reg <= and_ln48_reg_1315;
        and_ln48_reg_1315_pp0_iter2_reg <= and_ln48_reg_1315_pp0_iter1_reg;
        dw_weights_addr_reg_1284 <= p_cast88_fu_490_p1;
        empty_31_reg_1274 <= empty_31_fu_495_p1;
        first_iter_0_reg_1270 <= first_iter_0_fu_462_p2;
        first_iter_1_mid2_reg_1266 <= first_iter_1_mid2_fu_446_p3;
        input_stream_read_reg_1299 <= input_stream_dout;
        input_stream_read_reg_1299_pp0_iter1_reg <= input_stream_read_reg_1299;
        line_buffer_addr_reg_1305 <= zext_ln29_fu_537_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (first_iter_0_reg_1270 == 1'd1) & (first_iter_1_mid2_reg_1266 == 1'd1))) begin
        dw_weights_load3467_fu_136 <= dw_weights_q1;
        dw_weights_load_32270_fu_148 <= dw_weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (first_iter_0_reg_1270 == 1'd1) & (first_iter_1_mid2_reg_1266 == 1'd1))) begin
        dw_weights_load_13068_fu_140 <= dw_weights_q1;
        dw_weights_load_22669_fu_144 <= dw_weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (first_iter_0_reg_1270 == 1'd1) & (first_iter_1_mid2_reg_1266 == 1'd1))) begin
        dw_weights_load_41871_fu_152 <= dw_weights_q1;
        dw_weights_load_51472_fu_156 <= dw_weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (first_iter_0_reg_1270 == 1'd1) & (first_iter_1_mid2_reg_1266 == 1'd1))) begin
        dw_weights_load_61073_fu_160 <= dw_weights_q1;
        dw_weights_load_7674_fu_164 <= dw_weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (first_iter_0_reg_1270 == 1'd1) & (first_iter_1_mid2_reg_1266 == 1'd1))) begin
        dw_weights_load_8275_fu_168 <= dw_weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_fu_172 <= input_stream_read_reg_1299_pp0_iter1_reg;
        p_0_0_083_2_19277_fu_124 <= empty_fu_172;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        first_iter_1_reg_1319 <= first_iter_1_fu_585_p2;
        icmp_ln28_reg_1329 <= icmp_ln28_fu_597_p2;
        icmp_ln29_reg_1324 <= icmp_ln29_fu_591_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        icmp_ln27_reg_1416 <= icmp_ln27_fu_812_p2;
        icmp_ln27_reg_1416_pp0_iter1_reg <= icmp_ln27_reg_1416;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_1_load_reg_1345 <= line_buffer_1_q0;
        line_buffer_load_reg_1339 <= line_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        p_0_0_083_1138881_fu_132 <= p_0_0_0858980_load_reg_1351;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_083_1_19079_fu_128 <= p_0_0_085_19178_fu_176;
        p_0_0_085_19178_fu_176 <= line_buffer_1_load_reg_1345;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_0_0_0858980_fu_180 <= line_buffer_load_reg_1339;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        p_0_0_0858980_load_reg_1351 <= p_0_0_0858980_fu_180;
    end
end

always @ (*) begin
    if (((icmp_ln27_fu_812_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln27_reg_1416_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter2_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_992)) begin
            ap_phi_mux_first_iter_182_phi_fu_336_p4 = first_iter_1_reg_1319;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_first_iter_182_phi_fu_336_p4 = 1'd1;
        end else begin
            ap_phi_mux_first_iter_182_phi_fu_336_p4 = first_iter_1_reg_1319;
        end
    end else begin
        ap_phi_mux_first_iter_182_phi_fu_336_p4 = first_iter_1_reg_1319;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_992)) begin
            ap_phi_mux_icmp_ln2884_phi_fu_316_p4 = icmp_ln28_reg_1329;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln2884_phi_fu_316_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln2884_phi_fu_316_p4 = icmp_ln28_reg_1329;
        end
    end else begin
        ap_phi_mux_icmp_ln2884_phi_fu_316_p4 = icmp_ln28_reg_1329;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_992)) begin
            ap_phi_mux_icmp_ln2983_phi_fu_326_p4 = icmp_ln29_reg_1324;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln2983_phi_fu_326_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln2983_phi_fu_326_p4 = icmp_ln29_reg_1324;
        end
    end else begin
        ap_phi_mux_icmp_ln2983_phi_fu_326_p4 = icmp_ln29_reg_1324;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c76_load = 6'd0;
    end else begin
        ap_sig_allocacmp_c76_load = c76_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ch64_load = 6'd0;
    end else begin
        ap_sig_allocacmp_ch64_load = ch64_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten65_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten65_load = indvar_flatten65_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r66_load = 6'd0;
    end else begin
        ap_sig_allocacmp_r66_load = r66_fu_116;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        dw_weights_address0_local = p_cast96_fu_739_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dw_weights_address0_local = p_cast95_fu_706_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dw_weights_address0_local = p_cast93_fu_661_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dw_weights_address0_local = p_cast91_fu_628_p1;
    end else if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dw_weights_address0_local = p_cast90_fu_516_p1;
    end else begin
        dw_weights_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        dw_weights_address1_local = p_cast94_fu_696_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dw_weights_address1_local = p_cast92_fu_651_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dw_weights_address1_local = dw_weights_addr_reg_1284;
    end else if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dw_weights_address1_local = p_cast89_fu_505_p1;
    end else begin
        dw_weights_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dw_weights_ce0_local = 1'b1;
    end else begin
        dw_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dw_weights_ce1_local = 1'b1;
    end else begin
        dw_weights_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1068_ce = 1'b1;
    end else begin
        grp_fu_1068_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1077_ce = 1'b1;
    end else begin
        grp_fu_1077_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1086_ce = 1'b1;
    end else begin
        grp_fu_1086_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1095_ce = 1'b1;
    end else begin
        grp_fu_1095_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1104_ce = 1'b1;
    end else begin
        grp_fu_1104_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1113_ce = 1'b1;
    end else begin
        grp_fu_1113_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1122_ce = 1'b1;
    end else begin
        grp_fu_1122_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1131_ce = 1'b1;
    end else begin
        grp_fu_1131_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_blk_n = input_stream_empty_n;
    end else begin
        input_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_read = 1'b1;
    end else begin
        input_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln48_reg_1315_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage2_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        internal_fifo_blk_n = internal_fifo_full_n;
    end else begin
        internal_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln48_reg_1315_pp0_iter2_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        internal_fifo_write = 1'b1;
    end else begin
        internal_fifo_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_ce0_local = 1'b1;
    end else begin
        line_buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_we0_local = 1'b1;
    end else begin
        line_buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_address0_local = line_buffer_addr_reg_1305;
    end else if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_address0_local = zext_ln29_fu_537_p1;
    end else begin
        line_buffer_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        line_buffer_ce0_local = 1'b1;
    end else begin
        line_buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        line_buffer_we0_local = 1'b1;
    end else begin
        line_buffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln27_1_fu_744_p2 = (indvar_flatten7863_fu_104 + 17'd1);

assign add_ln27_fu_380_p2 = (ap_sig_allocacmp_ch64_load + 6'd1);

assign add_ln28_1_fu_571_p2 = (ap_sig_allocacmp_indvar_flatten65_load + 12'd1);

assign and_ln27_fu_406_p2 = (xor_ln27_fu_400_p2 & ap_phi_mux_icmp_ln2983_phi_fu_326_p4);

assign and_ln48_fu_559_p2 = (icmp_ln48_fu_553_p2 & icmp_fu_531_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp0 = ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp0 = ((ap_done_reg == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001_grp2 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage2_iter2_grp2));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage2_iter2_grp2));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage2_iter2_grp2));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = (ap_done_reg == 1'b1);
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_pp0_stage2_iter2_grp2 = ((internal_fifo_full_n == 1'b0) & (1'd1 == and_ln48_reg_1315_pp0_iter2_reg));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (input_stream_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_177 = ((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_992 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln27_reg_1416 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign ap_ready = ap_ready_sig;

assign c_fu_565_p2 = (c_mid2_fu_432_p3 + 6'd1);

assign c_mid2_fu_432_p3 = ((empty_29_fu_426_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_c76_load);

assign ch_fu_412_p3 = ((ap_phi_mux_icmp_ln2884_phi_fu_316_p4[0:0] == 1'b1) ? add_ln27_fu_380_p2 : ap_sig_allocacmp_ch64_load);

assign dw_weights_address0 = dw_weights_address0_local;

assign dw_weights_address1 = dw_weights_address1_local;

assign dw_weights_ce0 = dw_weights_ce0_local;

assign dw_weights_ce1 = dw_weights_ce1_local;

assign empty_29_fu_426_p2 = (ap_phi_mux_icmp_ln2884_phi_fu_316_p4 | and_ln27_fu_406_p2);

assign empty_30_fu_484_p2 = (p_shl_fu_480_p1 + select_ln27_1_cast_fu_468_p1);

assign empty_31_fu_495_p1 = empty_30_fu_484_p2[8:0];

assign empty_32_fu_499_p2 = (empty_31_fu_495_p1 + 9'd1);

assign empty_33_fu_510_p2 = (empty_31_fu_495_p1 + 9'd2);

assign empty_34_fu_623_p2 = (empty_31_reg_1274 + 9'd3);

assign empty_35_fu_646_p2 = (empty_31_reg_1274 + 9'd4);

assign empty_36_fu_656_p2 = (empty_31_reg_1274 + 9'd5);

assign empty_37_fu_691_p2 = (empty_31_reg_1274 + 9'd6);

assign empty_38_fu_701_p2 = (empty_31_reg_1274 + 9'd7);

assign empty_39_fu_734_p2 = (empty_31_reg_1274 + 9'd8);

assign first_iter_0_fu_462_p2 = ((c_mid2_fu_432_p3 == 6'd0) ? 1'b1 : 1'b0);

assign first_iter_1_fu_585_p2 = ((r_fu_454_p3 == 6'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid1_fu_440_p2 = ((r_3_fu_420_p2 == 6'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid2_fu_446_p3 = ((and_ln27_fu_406_p2[0:0] == 1'b1) ? first_iter_1_mid1_fu_440_p2 : or_ln27_fu_394_p2);

assign grp_fu_1068_p2 = {{tmp_fu_790_p4}, {8'd0}};

assign grp_fu_1077_p2 = {{tmp_s_fu_842_p4}, {8'd0}};

assign grp_fu_1086_p2 = {{tmp_62_fu_879_p4}, {8'd0}};

assign grp_fu_1095_p2 = {{tmp_63_fu_909_p4}, {8'd0}};

assign grp_fu_1104_p2 = {{tmp_64_fu_940_p4}, {8'd0}};

assign grp_fu_1113_p2 = {{tmp_65_fu_977_p4}, {8'd0}};

assign grp_fu_1122_p2 = {{tmp_66_fu_997_p4}, {8'd0}};

assign grp_fu_1131_p2 = {{tmp_67_fu_1014_p4}, {8'd0}};

assign icmp_fu_531_p2 = ((tmp_2_fu_521_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_812_p2 = ((indvar_flatten7863_fu_104 == 17'd100351) ? 1'b1 : 1'b0);

assign icmp_ln28_fu_597_p2 = ((select_ln28_1_fu_577_p3 == 12'd3136) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_591_p2 = ((c_fu_565_p2 == 6'd56) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_553_p2 = ((tmp_3_fu_543_p4 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_1049_p2 = (($signed(trunc_ln_fu_1031_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign internal_fifo_din = select_ln55_fu_1055_p3;

assign line_buffer_1_address0 = zext_ln29_fu_537_p1;

assign or_ln27_fu_394_p2 = (ap_phi_mux_icmp_ln2884_phi_fu_316_p4 | ap_phi_mux_first_iter_182_phi_fu_336_p4);

assign p_cast88_fu_490_p1 = empty_30_fu_484_p2;

assign p_cast89_fu_505_p1 = empty_32_fu_499_p2;

assign p_cast90_fu_516_p1 = empty_33_fu_510_p2;

assign p_cast91_fu_628_p1 = empty_34_fu_623_p2;

assign p_cast92_fu_651_p1 = empty_35_fu_646_p2;

assign p_cast93_fu_661_p1 = empty_36_fu_656_p2;

assign p_cast94_fu_696_p1 = empty_37_fu_691_p2;

assign p_cast95_fu_706_p1 = empty_38_fu_701_p2;

assign p_cast96_fu_739_p1 = empty_39_fu_734_p2;

assign p_shl_fu_480_p1 = tmp_1_fu_472_p3;

assign r_3_fu_420_p2 = (select_ln27_fu_386_p3 + 6'd1);

assign r_fu_454_p3 = ((and_ln27_fu_406_p2[0:0] == 1'b1) ? r_3_fu_420_p2 : select_ln27_fu_386_p3);

assign select_ln27_1_cast_fu_468_p1 = ch_fu_412_p3;

assign select_ln27_fu_386_p3 = ((ap_phi_mux_icmp_ln2884_phi_fu_316_p4[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_r66_load);

assign select_ln28_1_fu_577_p3 = ((ap_phi_mux_icmp_ln2884_phi_fu_316_p4[0:0] == 1'b1) ? 12'd1 : add_ln28_1_fu_571_p2);

assign select_ln55_fu_1055_p3 = ((icmp_ln55_fu_1049_p2[0:0] == 1'b1) ? trunc_ln2_fu_1040_p4 : 15'd0);

assign sext_ln52_10_fu_683_p0 = p_0_0_0858980_fu_180;

assign sext_ln52_12_fu_808_p0 = p_0_0_083_1_19079_fu_128;

assign sext_ln52_13_fu_859_p0 = p_0_0_085_19178_fu_176;

assign sext_ln52_15_fu_926_p0 = p_0_0_083_2_19277_fu_124;

assign sext_ln52_16_fu_957_p0 = empty_fu_172;

assign sext_ln52_9_fu_780_p0 = p_0_0_083_1138881_fu_132;

assign tmp_1_fu_472_p3 = {{ch_fu_412_p3}, {3'd0}};

assign tmp_2_fu_521_p4 = {{r_fu_454_p3[5:1]}};

assign tmp_3_fu_543_p4 = {{c_mid2_fu_432_p3[5:1]}};

assign tmp_62_fu_879_p1 = grp_fu_1077_p3;

assign tmp_62_fu_879_p4 = {{tmp_62_fu_879_p1[23:8]}};

assign tmp_63_fu_909_p1 = grp_fu_1086_p3;

assign tmp_63_fu_909_p4 = {{tmp_63_fu_909_p1[23:8]}};

assign tmp_64_fu_940_p1 = grp_fu_1095_p3;

assign tmp_64_fu_940_p4 = {{tmp_64_fu_940_p1[23:8]}};

assign tmp_65_fu_977_p1 = grp_fu_1104_p3;

assign tmp_65_fu_977_p4 = {{tmp_65_fu_977_p1[23:8]}};

assign tmp_66_fu_997_p1 = grp_fu_1113_p3;

assign tmp_66_fu_997_p4 = {{tmp_66_fu_997_p1[23:8]}};

assign tmp_67_fu_1014_p1 = grp_fu_1122_p3;

assign tmp_67_fu_1014_p4 = {{tmp_67_fu_1014_p1[23:8]}};

assign tmp_fu_790_p4 = {{mul_ln52_fu_784_p2[23:8]}};

assign tmp_s_fu_842_p1 = grp_fu_1068_p3;

assign tmp_s_fu_842_p4 = {{tmp_s_fu_842_p1[23:8]}};

assign trunc_ln2_fu_1040_p1 = grp_fu_1131_p3;

assign trunc_ln2_fu_1040_p4 = {{trunc_ln2_fu_1040_p1[22:8]}};

assign trunc_ln_fu_1031_p1 = grp_fu_1131_p3;

assign trunc_ln_fu_1031_p4 = {{trunc_ln_fu_1031_p1[23:8]}};

assign xor_ln27_fu_400_p2 = (ap_phi_mux_icmp_ln2884_phi_fu_316_p4 ^ 1'd1);

assign zext_ln29_fu_537_p1 = c_mid2_fu_432_p3;

endmodule //mobilenetv2_block_depthwise_conv
