// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mobilenetv2_block_pointwise_conv (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        internal_fifo_dout,
        internal_fifo_empty_n,
        internal_fifo_read,
        internal_fifo_num_data_valid,
        internal_fifo_fifo_cap,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        output_tensor,
        pw_weights_address0,
        pw_weights_ce0,
        pw_weights_q0,
        pw_weights_address1,
        pw_weights_ce1,
        pw_weights_q1
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] internal_fifo_dout;
input   internal_fifo_empty_n;
output   internal_fifo_read;
input  [6:0] internal_fifo_num_data_valid;
input  [6:0] internal_fifo_fifo_cap;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [15:0] m_axi_gmem1_0_WDATA;
output  [1:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [15:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [9:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [63:0] output_tensor;
output  [9:0] pw_weights_address0;
output   pw_weights_ce0;
input  [15:0] pw_weights_q0;
output  [9:0] pw_weights_address1;
output   pw_weights_ce1;
input  [15:0] pw_weights_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] output_tensor_read_reg_542;
reg    ap_block_state1;
wire   [11:0] add_ln72_1_fu_481_p2;
reg   [11:0] add_ln72_1_reg_710;
wire    ap_CS_fsm_state2;
wire   [5:0] add_ln72_fu_493_p2;
reg   [5:0] add_ln72_reg_718;
wire   [5:0] add_ln73_fu_505_p2;
reg   [5:0] add_ln73_reg_726;
wire    ap_CS_fsm_state3;
wire   [11:0] thr_add_fu_515_p2;
reg   [11:0] thr_add_reg_731;
reg   [15:0] pixel_channels_load_reg_736;
wire    ap_CS_fsm_state6;
reg   [15:0] pixel_channels_load_1_reg_741;
reg   [15:0] pixel_channels_load_2_reg_746;
wire    ap_CS_fsm_state7;
reg   [15:0] pixel_channels_load_3_reg_751;
reg   [15:0] pixel_channels_load_4_reg_756;
wire    ap_CS_fsm_state8;
reg   [15:0] pixel_channels_load_5_reg_761;
reg   [15:0] pixel_channels_load_6_reg_766;
wire    ap_CS_fsm_state9;
reg   [15:0] pixel_channels_load_7_reg_771;
reg   [15:0] pixel_channels_load_8_reg_776;
wire    ap_CS_fsm_state10;
reg   [15:0] pixel_channels_load_9_reg_781;
reg   [15:0] pixel_channels_load_10_reg_786;
wire    ap_CS_fsm_state11;
reg   [15:0] pixel_channels_load_11_reg_791;
reg   [15:0] pixel_channels_load_12_reg_796;
wire    ap_CS_fsm_state12;
reg   [15:0] pixel_channels_load_13_reg_801;
reg   [15:0] pixel_channels_load_14_reg_806;
wire    ap_CS_fsm_state13;
reg   [15:0] pixel_channels_load_15_reg_811;
reg   [15:0] pixel_channels_load_16_reg_816;
wire    ap_CS_fsm_state14;
reg   [15:0] pixel_channels_load_17_reg_821;
reg   [15:0] pixel_channels_load_18_reg_826;
wire    ap_CS_fsm_state15;
reg   [15:0] pixel_channels_load_19_reg_831;
reg   [15:0] pixel_channels_load_20_reg_836;
wire    ap_CS_fsm_state16;
reg   [15:0] pixel_channels_load_21_reg_841;
reg   [15:0] pixel_channels_load_22_reg_846;
wire    ap_CS_fsm_state17;
reg   [15:0] pixel_channels_load_23_reg_851;
reg   [15:0] pixel_channels_load_24_reg_856;
wire    ap_CS_fsm_state18;
reg   [15:0] pixel_channels_load_25_reg_861;
reg   [15:0] pixel_channels_load_26_reg_866;
wire    ap_CS_fsm_state19;
reg   [15:0] pixel_channels_load_27_reg_871;
reg   [15:0] pixel_channels_load_28_reg_876;
wire    ap_CS_fsm_state20;
reg   [15:0] pixel_channels_load_29_reg_881;
reg   [15:0] pixel_channels_load_30_reg_886;
wire    ap_CS_fsm_state21;
reg   [15:0] pixel_channels_load_31_reg_891;
reg   [4:0] pixel_channels_address0;
reg    pixel_channels_ce0;
reg    pixel_channels_we0;
wire   [15:0] pixel_channels_q0;
wire   [15:0] pixel_channels_q1;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_idle;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_ready;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_internal_fifo_read;
wire   [4:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_address0;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_ce0;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_we0;
wire   [15:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_d0;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_idle;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_ready;
wire   [9:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address0;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce0;
wire   [9:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address1;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce1;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWID;
wire   [31:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWUSER;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WVALID;
wire   [15:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WDATA;
wire   [1:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WSTRB;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WID;
wire   [0:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WUSER;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARID;
wire   [31:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARUSER;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_RREADY;
wire    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_BREADY;
reg   [5:0] c_reg_403;
wire   [0:0] icmp_ln72_fu_487_p2;
wire    ap_CS_fsm_state22;
reg    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg;
wire   [0:0] icmp_ln73_fu_499_p2;
wire    ap_CS_fsm_state4;
reg    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg;
reg   [11:0] phi_mul390_fu_120;
reg   [5:0] r_fu_124;
reg    pixel_channels_ce1_local;
wire    ap_CS_fsm_state5;
reg   [4:0] pixel_channels_address1_local;
reg    pixel_channels_ce0_local;
reg   [4:0] pixel_channels_address0_local;
wire   [11:0] zext_ln73_fu_511_p1;
reg   [21:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 22'd1;
#0 grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg = 1'b0;
#0 grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg = 1'b0;
#0 phi_mul390_fu_120 = 12'd0;
#0 r_fu_124 = 6'd0;
end

mobilenetv2_block_pointwise_conv_pixel_channels_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
pixel_channels_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pixel_channels_address0),
    .ce0(pixel_channels_ce0),
    .we0(pixel_channels_we0),
    .d0(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_d0),
    .q0(pixel_channels_q0),
    .address1(pixel_channels_address1_local),
    .ce1(pixel_channels_ce1_local),
    .q1(pixel_channels_q1)
);

mobilenetv2_block_pointwise_conv_Pipeline_VITIS_LOOP_77_3 grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start),
    .ap_done(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done),
    .ap_idle(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_idle),
    .ap_ready(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_ready),
    .internal_fifo_dout(internal_fifo_dout),
    .internal_fifo_empty_n(internal_fifo_empty_n),
    .internal_fifo_read(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_internal_fifo_read),
    .internal_fifo_num_data_valid(7'd0),
    .internal_fifo_fifo_cap(7'd0),
    .pixel_channels_address0(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_address0),
    .pixel_channels_ce0(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_ce0),
    .pixel_channels_we0(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_we0),
    .pixel_channels_d0(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_d0)
);

mobilenetv2_block_pointwise_conv_Pipeline_VITIS_LOOP_83_4 grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start),
    .ap_done(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done),
    .ap_idle(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_idle),
    .ap_ready(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_ready),
    .pw_weights_address0(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address0),
    .pw_weights_ce0(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce0),
    .pw_weights_q0(pw_weights_q0),
    .pw_weights_address1(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address1),
    .pw_weights_ce1(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce1),
    .pw_weights_q1(pw_weights_q1),
    .sext_ln87_2(pixel_channels_load_reg_736),
    .sext_ln87_4(pixel_channels_load_1_reg_741),
    .sext_ln87_6(pixel_channels_load_2_reg_746),
    .sext_ln87_8(pixel_channels_load_3_reg_751),
    .sext_ln87_10(pixel_channels_load_4_reg_756),
    .sext_ln87_12(pixel_channels_load_5_reg_761),
    .sext_ln87_14(pixel_channels_load_6_reg_766),
    .sext_ln87_16(pixel_channels_load_7_reg_771),
    .sext_ln87_18(pixel_channels_load_8_reg_776),
    .sext_ln87_20(pixel_channels_load_9_reg_781),
    .sext_ln87_22(pixel_channels_load_10_reg_786),
    .sext_ln87_24(pixel_channels_load_11_reg_791),
    .sext_ln87_26(pixel_channels_load_12_reg_796),
    .sext_ln87_28(pixel_channels_load_13_reg_801),
    .sext_ln87_30(pixel_channels_load_14_reg_806),
    .sext_ln87_32(pixel_channels_load_15_reg_811),
    .sext_ln87_34(pixel_channels_load_16_reg_816),
    .sext_ln87_36(pixel_channels_load_17_reg_821),
    .sext_ln87_38(pixel_channels_load_18_reg_826),
    .sext_ln87_40(pixel_channels_load_19_reg_831),
    .sext_ln87_42(pixel_channels_load_20_reg_836),
    .sext_ln87_44(pixel_channels_load_21_reg_841),
    .sext_ln87_46(pixel_channels_load_22_reg_846),
    .sext_ln87_48(pixel_channels_load_23_reg_851),
    .sext_ln87_50(pixel_channels_load_24_reg_856),
    .sext_ln87_52(pixel_channels_load_25_reg_861),
    .sext_ln87_54(pixel_channels_load_26_reg_866),
    .sext_ln87_56(pixel_channels_load_27_reg_871),
    .sext_ln87_58(pixel_channels_load_28_reg_876),
    .sext_ln87_60(pixel_channels_load_29_reg_881),
    .sext_ln87_62(pixel_channels_load_30_reg_886),
    .sext_ln87_63(pixel_channels_load_31_reg_891),
    .zext_ln83(thr_add_reg_731),
    .output_tensor(output_tensor_read_reg_542),
    .m_axi_gmem1_0_AWVALID(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(m_axi_gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(m_axi_gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(16'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(10'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(m_axi_gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(m_axi_gmem1_0_BRESP),
    .m_axi_gmem1_0_BID(m_axi_gmem1_0_BID),
    .m_axi_gmem1_0_BUSER(m_axi_gmem1_0_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln72_fu_487_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln73_fu_499_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg <= 1'b1;
        end else if ((grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_ready == 1'b1)) begin
            grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg <= 1'b1;
        end else if ((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_ready == 1'b1)) begin
            grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
        c_reg_403 <= add_ln73_reg_726;
    end else if (((icmp_ln72_fu_487_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        c_reg_403 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        phi_mul390_fu_120 <= 12'd0;
    end else if (((icmp_ln73_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_mul390_fu_120 <= add_ln72_1_reg_710;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        r_fu_124 <= 6'd0;
    end else if (((icmp_ln73_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        r_fu_124 <= add_ln72_reg_718;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln72_1_reg_710 <= add_ln72_1_fu_481_p2;
        add_ln72_reg_718 <= add_ln72_fu_493_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln73_reg_726 <= add_ln73_fu_505_p2;
        thr_add_reg_731 <= thr_add_fu_515_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        output_tensor_read_reg_542 <= output_tensor;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        pixel_channels_load_10_reg_786 <= pixel_channels_q1;
        pixel_channels_load_11_reg_791 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        pixel_channels_load_12_reg_796 <= pixel_channels_q1;
        pixel_channels_load_13_reg_801 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        pixel_channels_load_14_reg_806 <= pixel_channels_q1;
        pixel_channels_load_15_reg_811 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        pixel_channels_load_16_reg_816 <= pixel_channels_q1;
        pixel_channels_load_17_reg_821 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        pixel_channels_load_18_reg_826 <= pixel_channels_q1;
        pixel_channels_load_19_reg_831 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pixel_channels_load_1_reg_741 <= pixel_channels_q0;
        pixel_channels_load_reg_736 <= pixel_channels_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        pixel_channels_load_20_reg_836 <= pixel_channels_q1;
        pixel_channels_load_21_reg_841 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        pixel_channels_load_22_reg_846 <= pixel_channels_q1;
        pixel_channels_load_23_reg_851 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        pixel_channels_load_24_reg_856 <= pixel_channels_q1;
        pixel_channels_load_25_reg_861 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        pixel_channels_load_26_reg_866 <= pixel_channels_q1;
        pixel_channels_load_27_reg_871 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        pixel_channels_load_28_reg_876 <= pixel_channels_q1;
        pixel_channels_load_29_reg_881 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        pixel_channels_load_2_reg_746 <= pixel_channels_q1;
        pixel_channels_load_3_reg_751 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        pixel_channels_load_30_reg_886 <= pixel_channels_q1;
        pixel_channels_load_31_reg_891 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pixel_channels_load_4_reg_756 <= pixel_channels_q1;
        pixel_channels_load_5_reg_761 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        pixel_channels_load_6_reg_766 <= pixel_channels_q1;
        pixel_channels_load_7_reg_771 <= pixel_channels_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        pixel_channels_load_8_reg_776 <= pixel_channels_q1;
        pixel_channels_load_9_reg_781 <= pixel_channels_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if ((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done == 1'b0)) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln72_fu_487_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln72_fu_487_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixel_channels_address0 = grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_address0;
    end else begin
        pixel_channels_address0 = pixel_channels_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        pixel_channels_address0_local = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        pixel_channels_address0_local = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        pixel_channels_address0_local = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        pixel_channels_address0_local = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        pixel_channels_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        pixel_channels_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        pixel_channels_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        pixel_channels_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        pixel_channels_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        pixel_channels_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        pixel_channels_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        pixel_channels_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        pixel_channels_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        pixel_channels_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pixel_channels_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        pixel_channels_address0_local = 64'd1;
    end else begin
        pixel_channels_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        pixel_channels_address1_local = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        pixel_channels_address1_local = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        pixel_channels_address1_local = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        pixel_channels_address1_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        pixel_channels_address1_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        pixel_channels_address1_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        pixel_channels_address1_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        pixel_channels_address1_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        pixel_channels_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        pixel_channels_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        pixel_channels_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        pixel_channels_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        pixel_channels_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        pixel_channels_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pixel_channels_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        pixel_channels_address1_local = 64'd0;
    end else begin
        pixel_channels_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixel_channels_ce0 = grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_ce0;
    end else begin
        pixel_channels_ce0 = pixel_channels_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        pixel_channels_ce0_local = 1'b1;
    end else begin
        pixel_channels_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        pixel_channels_ce1_local = 1'b1;
    end else begin
        pixel_channels_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixel_channels_we0 = grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_we0;
    end else begin
        pixel_channels_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln72_fu_487_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln73_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln72_1_fu_481_p2 = (phi_mul390_fu_120 + 12'd54);

assign add_ln72_fu_493_p2 = (r_fu_124 + 6'd1);

assign add_ln73_fu_505_p2 = (c_reg_403 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start = grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg;

assign grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg;

assign icmp_ln72_fu_487_p2 = ((r_fu_124 == 6'd54) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_499_p2 = ((c_reg_403 == 6'd54) ? 1'b1 : 1'b0);

assign internal_fifo_read = grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_internal_fifo_read;

assign m_axi_gmem1_0_ARADDR = 64'd0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 32'd0;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_ARVALID = 1'b0;

assign m_axi_gmem1_0_AWADDR = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWADDR;

assign m_axi_gmem1_0_AWBURST = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWBURST;

assign m_axi_gmem1_0_AWCACHE = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWCACHE;

assign m_axi_gmem1_0_AWID = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWID;

assign m_axi_gmem1_0_AWLEN = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLEN;

assign m_axi_gmem1_0_AWLOCK = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLOCK;

assign m_axi_gmem1_0_AWPROT = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWPROT;

assign m_axi_gmem1_0_AWQOS = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWQOS;

assign m_axi_gmem1_0_AWREGION = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWREGION;

assign m_axi_gmem1_0_AWSIZE = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWSIZE;

assign m_axi_gmem1_0_AWUSER = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWUSER;

assign m_axi_gmem1_0_AWVALID = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWVALID;

assign m_axi_gmem1_0_BREADY = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_BREADY;

assign m_axi_gmem1_0_RREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WDATA;

assign m_axi_gmem1_0_WID = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WID;

assign m_axi_gmem1_0_WLAST = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WLAST;

assign m_axi_gmem1_0_WSTRB = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WSTRB;

assign m_axi_gmem1_0_WUSER = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WUSER;

assign m_axi_gmem1_0_WVALID = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WVALID;

assign pw_weights_address0 = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address0;

assign pw_weights_address1 = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address1;

assign pw_weights_ce0 = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce0;

assign pw_weights_ce1 = grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce1;

assign thr_add_fu_515_p2 = (phi_mul390_fu_120 + zext_ln73_fu_511_p1);

assign zext_ln73_fu_511_p1 = c_reg_403;

endmodule //mobilenetv2_block_pointwise_conv
