

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "6", "19", "57", "58"],
		"CDFG" : "mobilenetv2_block",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1726402", "EstimateLatencyMax" : "1726402",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "4", "Name" : "Loop_VITIS_LOOP_117_1_proc_U0"},
			{"ID" : "6", "Name" : "depthwise_conv_U0"},
			{"ID" : "19", "Name" : "pointwise_conv_U0"}],
		"OutputProcess" : [
			{"ID" : "19", "Name" : "pointwise_conv_U0"}],
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "4", "SubInstance" : "Loop_VITIS_LOOP_117_1_proc_U0", "Port" : "gmem0"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "pointwise_conv_U0", "Port" : "gmem1"}]},
			{"Name" : "input_tensor", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_tensor", "Type" : "None", "Direction" : "I"},
			{"Name" : "dw_weights", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "6", "SubInstance" : "depthwise_conv_U0", "Port" : "dw_weights"}]},
			{"Name" : "pw_weights", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "pointwise_conv_U0", "Port" : "pw_weights"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_117_1_proc_U0", "Parent" : "0", "Child" : ["5"],
		"CDFG" : "Loop_VITIS_LOOP_117_1_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "100363", "EstimateLatencyMax" : "100363",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_tensor", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "input_stream", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["6"], "DependentChan" : "57", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "input_stream_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_117_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter10", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter10", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Loop_VITIS_LOOP_117_1_proc_U0.flow_control_loop_pipe_U", "Parent" : "4"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0", "Parent" : "0", "Child" : ["7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18"],
		"CDFG" : "depthwise_conv",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "501769", "EstimateLatencyMax" : "501769",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "input_stream", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["4"], "DependentChan" : "57", "DependentChanDepth" : "2", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "input_stream_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "internal_fifo", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["19"], "DependentChan" : "58", "DependentChanDepth" : "64", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "internal_fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "dw_weights", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_27_1_VITIS_LOOP_28_2_VITIS_LOOP_29_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage2", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage2_subdone", "QuitState" : "ap_ST_fsm_pp0_stage2", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage2_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.line_buffer_U", "Parent" : "6"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.line_buffer_1_U", "Parent" : "6"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mul_16s_16s_24_1_1_U4", "Parent" : "6"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U5", "Parent" : "6"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U6", "Parent" : "6"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U7", "Parent" : "6"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U8", "Parent" : "6"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U9", "Parent" : "6"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U10", "Parent" : "6"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U11", "Parent" : "6"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.mac_muladd_16s_16s_24ns_24_4_1_U12", "Parent" : "6"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.depthwise_conv_U0.flow_control_loop_pipe_U", "Parent" : "6"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0", "Parent" : "0", "Child" : ["20", "21", "23"],
		"CDFG" : "pointwise_conv",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1726381", "EstimateLatencyMax" : "1726381",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "internal_fifo", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["6"], "DependentChan" : "58", "DependentChanDepth" : "64", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "21", "SubInstance" : "grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414", "Port" : "internal_fifo", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421", "Port" : "gmem1", "Inst_start_state" : "21", "Inst_end_state" : "22"}]},
			{"Name" : "output_tensor", "Type" : "None", "Direction" : "I"},
			{"Name" : "pw_weights", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "23", "SubInstance" : "grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421", "Port" : "pw_weights", "Inst_start_state" : "21", "Inst_end_state" : "22"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_73_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "22", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state22"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_72_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "22", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.pixel_channels_U", "Parent" : "19"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414", "Parent" : "19", "Child" : ["22"],
		"CDFG" : "pointwise_conv_Pipeline_VITIS_LOOP_77_3",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "34", "EstimateLatencyMax" : "34",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "internal_fifo", "Type" : "Fifo", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "internal_fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "pixel_channels", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_77_3", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414.flow_control_loop_pipe_sequential_init_U", "Parent" : "21"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421", "Parent" : "19", "Child" : ["24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56"],
		"CDFG" : "pointwise_conv_Pipeline_VITIS_LOOP_83_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "538", "EstimateLatencyMax" : "538",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "pw_weights", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln87_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_14", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_16", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_18", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_20", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_22", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_24", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_26", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_28", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_30", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_32", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_34", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_36", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_38", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_40", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_42", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_44", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_46", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_48", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_50", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_52", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_54", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_56", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_58", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_60", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_62", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln87_63", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln83", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_tensor", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_B", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_83_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "16", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage8", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage8_subdone", "QuitState" : "ap_ST_fsm_pp0_stage8", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage8_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mul_16s_16s_24_1_1_U21", "Parent" : "23"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U22", "Parent" : "23"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U23", "Parent" : "23"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U24", "Parent" : "23"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U25", "Parent" : "23"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U26", "Parent" : "23"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U27", "Parent" : "23"},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U28", "Parent" : "23"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U29", "Parent" : "23"},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U30", "Parent" : "23"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U31", "Parent" : "23"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U32", "Parent" : "23"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U33", "Parent" : "23"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U34", "Parent" : "23"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U35", "Parent" : "23"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U36", "Parent" : "23"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U37", "Parent" : "23"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U38", "Parent" : "23"},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U39", "Parent" : "23"},
	{"ID" : "43", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U40", "Parent" : "23"},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U41", "Parent" : "23"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U42", "Parent" : "23"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U43", "Parent" : "23"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U44", "Parent" : "23"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U45", "Parent" : "23"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U46", "Parent" : "23"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U47", "Parent" : "23"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U48", "Parent" : "23"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U49", "Parent" : "23"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U50", "Parent" : "23"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U51", "Parent" : "23"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.mac_muladd_16s_16s_24ns_24_4_1_U52", "Parent" : "23"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.pointwise_conv_U0.grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421.flow_control_loop_pipe_sequential_init_U", "Parent" : "23"},
	{"ID" : "57", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.input_stream_U", "Parent" : "0"},
	{"ID" : "58", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.internal_fifo_U", "Parent" : "0"}]}
