-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mobilenetv2_block_pointwise_conv is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    internal_fifo_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    internal_fifo_empty_n : IN STD_LOGIC;
    internal_fifo_read : OUT STD_LOGIC;
    internal_fifo_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    internal_fifo_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    output_tensor : IN STD_LOGIC_VECTOR (63 downto 0);
    pw_weights_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pw_weights_ce0 : OUT STD_LOGIC;
    pw_weights_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pw_weights_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pw_weights_ce1 : OUT STD_LOGIC;
    pw_weights_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of mobilenetv2_block_pointwise_conv is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (21 downto 0) := "0000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (21 downto 0) := "0000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (21 downto 0) := "0000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (21 downto 0) := "0000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (21 downto 0) := "0000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (21 downto 0) := "0001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (21 downto 0) := "0010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (21 downto 0) := "0100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (21 downto 0) := "1000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv64_C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001100";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001110";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv64_10 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010000";
    constant ap_const_lv64_11 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010001";
    constant ap_const_lv64_12 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010010";
    constant ap_const_lv64_13 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010011";
    constant ap_const_lv64_14 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010100";
    constant ap_const_lv64_15 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010101";
    constant ap_const_lv64_16 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010110";
    constant ap_const_lv64_17 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010111";
    constant ap_const_lv64_18 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011000";
    constant ap_const_lv64_19 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011001";
    constant ap_const_lv64_1A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011010";
    constant ap_const_lv64_1B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011011";
    constant ap_const_lv64_1C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011100";
    constant ap_const_lv64_1D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011101";
    constant ap_const_lv64_1E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011110";
    constant ap_const_lv64_1F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_tensor_read_reg_542 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal add_ln72_1_fu_481_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln72_1_reg_710 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln72_fu_493_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln72_reg_718 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln73_fu_505_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln73_reg_726 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal thr_add_fu_515_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal thr_add_reg_731 : STD_LOGIC_VECTOR (11 downto 0);
    signal pixel_channels_load_reg_736 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal pixel_channels_load_1_reg_741 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_2_reg_746 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal pixel_channels_load_3_reg_751 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_4_reg_756 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal pixel_channels_load_5_reg_761 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_6_reg_766 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal pixel_channels_load_7_reg_771 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_8_reg_776 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal pixel_channels_load_9_reg_781 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_10_reg_786 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal pixel_channels_load_11_reg_791 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_12_reg_796 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal pixel_channels_load_13_reg_801 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_14_reg_806 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal pixel_channels_load_15_reg_811 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_16_reg_816 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal pixel_channels_load_17_reg_821 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_18_reg_826 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal pixel_channels_load_19_reg_831 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_20_reg_836 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal pixel_channels_load_21_reg_841 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_22_reg_846 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal pixel_channels_load_23_reg_851 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_24_reg_856 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal pixel_channels_load_25_reg_861 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_26_reg_866 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal pixel_channels_load_27_reg_871 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_28_reg_876 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal pixel_channels_load_29_reg_881 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_load_30_reg_886 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal pixel_channels_load_31_reg_891 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal pixel_channels_ce0 : STD_LOGIC;
    signal pixel_channels_we0 : STD_LOGIC;
    signal pixel_channels_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal pixel_channels_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_idle : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_ready : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_internal_fifo_read : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_ce0 : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_we0 : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_idle : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_ready : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce0 : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce1 : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWVALID : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WVALID : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WLAST : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARVALID : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_RREADY : STD_LOGIC;
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_BREADY : STD_LOGIC;
    signal c_reg_403 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln72_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln73_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg : STD_LOGIC := '0';
    signal phi_mul390_fu_120 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal r_fu_124 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal pixel_channels_ce1_local : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal pixel_channels_address1_local : STD_LOGIC_VECTOR (4 downto 0);
    signal pixel_channels_ce0_local : STD_LOGIC;
    signal pixel_channels_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln73_fu_511_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mobilenetv2_block_pointwise_conv_Pipeline_VITIS_LOOP_77_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        internal_fifo_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        internal_fifo_empty_n : IN STD_LOGIC;
        internal_fifo_read : OUT STD_LOGIC;
        internal_fifo_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        internal_fifo_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        pixel_channels_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        pixel_channels_ce0 : OUT STD_LOGIC;
        pixel_channels_we0 : OUT STD_LOGIC;
        pixel_channels_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component mobilenetv2_block_pointwise_conv_Pipeline_VITIS_LOOP_83_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pw_weights_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        pw_weights_ce0 : OUT STD_LOGIC;
        pw_weights_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        pw_weights_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        pw_weights_ce1 : OUT STD_LOGIC;
        pw_weights_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_10 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_12 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_14 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_16 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_18 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_20 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_22 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_24 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_26 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_28 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_30 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_32 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_34 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_36 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_38 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_40 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_42 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_44 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_46 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_48 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_50 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_52 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_54 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_56 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_58 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_60 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_62 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln87_63 : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln83 : IN STD_LOGIC_VECTOR (11 downto 0);
        output_tensor : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_WREADY : IN STD_LOGIC;
        m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RVALID : IN STD_LOGIC;
        m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_gmem1_0_RLAST : IN STD_LOGIC;
        m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
        m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BVALID : IN STD_LOGIC;
        m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component mobilenetv2_block_pointwise_conv_pixel_channels_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    pixel_channels_U : component mobilenetv2_block_pointwise_conv_pixel_channels_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pixel_channels_address0,
        ce0 => pixel_channels_ce0,
        we0 => pixel_channels_we0,
        d0 => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_d0,
        q0 => pixel_channels_q0,
        address1 => pixel_channels_address1_local,
        ce1 => pixel_channels_ce1_local,
        q1 => pixel_channels_q1);

    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414 : component mobilenetv2_block_pointwise_conv_Pipeline_VITIS_LOOP_77_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start,
        ap_done => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done,
        ap_idle => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_idle,
        ap_ready => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_ready,
        internal_fifo_dout => internal_fifo_dout,
        internal_fifo_empty_n => internal_fifo_empty_n,
        internal_fifo_read => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_internal_fifo_read,
        internal_fifo_num_data_valid => ap_const_lv7_0,
        internal_fifo_fifo_cap => ap_const_lv7_0,
        pixel_channels_address0 => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_address0,
        pixel_channels_ce0 => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_ce0,
        pixel_channels_we0 => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_we0,
        pixel_channels_d0 => grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_d0);

    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421 : component mobilenetv2_block_pointwise_conv_Pipeline_VITIS_LOOP_83_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start,
        ap_done => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done,
        ap_idle => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_idle,
        ap_ready => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_ready,
        pw_weights_address0 => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address0,
        pw_weights_ce0 => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce0,
        pw_weights_q0 => pw_weights_q0,
        pw_weights_address1 => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address1,
        pw_weights_ce1 => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce1,
        pw_weights_q1 => pw_weights_q1,
        sext_ln87_2 => pixel_channels_load_reg_736,
        sext_ln87_4 => pixel_channels_load_1_reg_741,
        sext_ln87_6 => pixel_channels_load_2_reg_746,
        sext_ln87_8 => pixel_channels_load_3_reg_751,
        sext_ln87_10 => pixel_channels_load_4_reg_756,
        sext_ln87_12 => pixel_channels_load_5_reg_761,
        sext_ln87_14 => pixel_channels_load_6_reg_766,
        sext_ln87_16 => pixel_channels_load_7_reg_771,
        sext_ln87_18 => pixel_channels_load_8_reg_776,
        sext_ln87_20 => pixel_channels_load_9_reg_781,
        sext_ln87_22 => pixel_channels_load_10_reg_786,
        sext_ln87_24 => pixel_channels_load_11_reg_791,
        sext_ln87_26 => pixel_channels_load_12_reg_796,
        sext_ln87_28 => pixel_channels_load_13_reg_801,
        sext_ln87_30 => pixel_channels_load_14_reg_806,
        sext_ln87_32 => pixel_channels_load_15_reg_811,
        sext_ln87_34 => pixel_channels_load_16_reg_816,
        sext_ln87_36 => pixel_channels_load_17_reg_821,
        sext_ln87_38 => pixel_channels_load_18_reg_826,
        sext_ln87_40 => pixel_channels_load_19_reg_831,
        sext_ln87_42 => pixel_channels_load_20_reg_836,
        sext_ln87_44 => pixel_channels_load_21_reg_841,
        sext_ln87_46 => pixel_channels_load_22_reg_846,
        sext_ln87_48 => pixel_channels_load_23_reg_851,
        sext_ln87_50 => pixel_channels_load_24_reg_856,
        sext_ln87_52 => pixel_channels_load_25_reg_861,
        sext_ln87_54 => pixel_channels_load_26_reg_866,
        sext_ln87_56 => pixel_channels_load_27_reg_871,
        sext_ln87_58 => pixel_channels_load_28_reg_876,
        sext_ln87_60 => pixel_channels_load_29_reg_881,
        sext_ln87_62 => pixel_channels_load_30_reg_886,
        sext_ln87_63 => pixel_channels_load_31_reg_891,
        zext_ln83 => thr_add_reg_731,
        output_tensor => output_tensor_read_reg_542,
        m_axi_gmem1_0_AWVALID => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY => m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY => m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY => ap_const_logic_0,
        m_axi_gmem1_0_ARADDR => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID => ap_const_logic_0,
        m_axi_gmem1_0_RREADY => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA => ap_const_lv16_0,
        m_axi_gmem1_0_RLAST => ap_const_logic_0,
        m_axi_gmem1_0_RID => ap_const_lv1_0,
        m_axi_gmem1_0_RFIFONUM => ap_const_lv10_0,
        m_axi_gmem1_0_RUSER => ap_const_lv1_0,
        m_axi_gmem1_0_RRESP => ap_const_lv2_0,
        m_axi_gmem1_0_BVALID => m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY => grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP => m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID => m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER => m_axi_gmem1_0_BUSER);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln72_fu_487_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln73_fu_499_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_ready = ap_const_logic_1)) then 
                    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_ready = ap_const_logic_1)) then 
                    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_reg_403_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then 
                c_reg_403 <= add_ln73_reg_726;
            elsif (((icmp_ln72_fu_487_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                c_reg_403 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    phi_mul390_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                phi_mul390_fu_120 <= ap_const_lv12_0;
            elsif (((icmp_ln73_fu_499_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                phi_mul390_fu_120 <= add_ln72_1_reg_710;
            end if; 
        end if;
    end process;

    r_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                r_fu_124 <= ap_const_lv6_0;
            elsif (((icmp_ln73_fu_499_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                r_fu_124 <= add_ln72_reg_718;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln72_1_reg_710 <= add_ln72_1_fu_481_p2;
                add_ln72_reg_718 <= add_ln72_fu_493_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln73_reg_726 <= add_ln73_fu_505_p2;
                thr_add_reg_731 <= thr_add_fu_515_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                output_tensor_read_reg_542 <= output_tensor;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                pixel_channels_load_10_reg_786 <= pixel_channels_q1;
                pixel_channels_load_11_reg_791 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                pixel_channels_load_12_reg_796 <= pixel_channels_q1;
                pixel_channels_load_13_reg_801 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                pixel_channels_load_14_reg_806 <= pixel_channels_q1;
                pixel_channels_load_15_reg_811 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                pixel_channels_load_16_reg_816 <= pixel_channels_q1;
                pixel_channels_load_17_reg_821 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                pixel_channels_load_18_reg_826 <= pixel_channels_q1;
                pixel_channels_load_19_reg_831 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                pixel_channels_load_1_reg_741 <= pixel_channels_q0;
                pixel_channels_load_reg_736 <= pixel_channels_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                pixel_channels_load_20_reg_836 <= pixel_channels_q1;
                pixel_channels_load_21_reg_841 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                pixel_channels_load_22_reg_846 <= pixel_channels_q1;
                pixel_channels_load_23_reg_851 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                pixel_channels_load_24_reg_856 <= pixel_channels_q1;
                pixel_channels_load_25_reg_861 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                pixel_channels_load_26_reg_866 <= pixel_channels_q1;
                pixel_channels_load_27_reg_871 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                pixel_channels_load_28_reg_876 <= pixel_channels_q1;
                pixel_channels_load_29_reg_881 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                pixel_channels_load_2_reg_746 <= pixel_channels_q1;
                pixel_channels_load_3_reg_751 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                pixel_channels_load_30_reg_886 <= pixel_channels_q1;
                pixel_channels_load_31_reg_891 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                pixel_channels_load_4_reg_756 <= pixel_channels_q1;
                pixel_channels_load_5_reg_761 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                pixel_channels_load_6_reg_766 <= pixel_channels_q1;
                pixel_channels_load_7_reg_771 <= pixel_channels_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                pixel_channels_load_8_reg_776 <= pixel_channels_q1;
                pixel_channels_load_9_reg_781 <= pixel_channels_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done, grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done, icmp_ln72_fu_487_p2, ap_CS_fsm_state22, icmp_ln73_fu_499_p2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln72_fu_487_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln73_fu_499_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                if (((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln72_1_fu_481_p2 <= std_logic_vector(unsigned(phi_mul390_fu_120) + unsigned(ap_const_lv12_36));
    add_ln72_fu_493_p2 <= std_logic_vector(unsigned(r_fu_124) + unsigned(ap_const_lv6_1));
    add_ln73_fu_505_p2 <= std_logic_vector(unsigned(c_reg_403) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;

    ap_ST_fsm_state22_blk_assign_proc : process(grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done)
    begin
        if ((grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state22_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state22_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done)
    begin
        if ((grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln72_fu_487_p2)
    begin
        if (((icmp_ln72_fu_487_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln72_fu_487_p2)
    begin
        if (((icmp_ln72_fu_487_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start <= grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_ap_start_reg;
    grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_ap_start_reg;
    icmp_ln72_fu_487_p2 <= "1" when (r_fu_124 = ap_const_lv6_36) else "0";
    icmp_ln73_fu_499_p2 <= "1" when (c_reg_403 = ap_const_lv6_36) else "0";
    internal_fifo_read <= grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_internal_fifo_read;
    m_axi_gmem1_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_ARID <= ap_const_lv1_0;
    m_axi_gmem1_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem1_0_AWADDR <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWADDR;
    m_axi_gmem1_0_AWBURST <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWBURST;
    m_axi_gmem1_0_AWCACHE <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWCACHE;
    m_axi_gmem1_0_AWID <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWID;
    m_axi_gmem1_0_AWLEN <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLEN;
    m_axi_gmem1_0_AWLOCK <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWLOCK;
    m_axi_gmem1_0_AWPROT <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWPROT;
    m_axi_gmem1_0_AWQOS <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWQOS;
    m_axi_gmem1_0_AWREGION <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWREGION;
    m_axi_gmem1_0_AWSIZE <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWSIZE;
    m_axi_gmem1_0_AWUSER <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWUSER;
    m_axi_gmem1_0_AWVALID <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_AWVALID;
    m_axi_gmem1_0_BREADY <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_BREADY;
    m_axi_gmem1_0_RREADY <= ap_const_logic_0;
    m_axi_gmem1_0_WDATA <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WDATA;
    m_axi_gmem1_0_WID <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WID;
    m_axi_gmem1_0_WLAST <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WLAST;
    m_axi_gmem1_0_WSTRB <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WSTRB;
    m_axi_gmem1_0_WUSER <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WUSER;
    m_axi_gmem1_0_WVALID <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_m_axi_gmem1_0_WVALID;

    pixel_channels_address0_assign_proc : process(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_address0, ap_CS_fsm_state4, pixel_channels_address0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pixel_channels_address0 <= grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_address0;
        else 
            pixel_channels_address0 <= pixel_channels_address0_local;
        end if; 
    end process;


    pixel_channels_address0_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            pixel_channels_address0_local <= ap_const_lv64_1F(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            pixel_channels_address0_local <= ap_const_lv64_1D(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            pixel_channels_address0_local <= ap_const_lv64_1B(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            pixel_channels_address0_local <= ap_const_lv64_19(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            pixel_channels_address0_local <= ap_const_lv64_17(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            pixel_channels_address0_local <= ap_const_lv64_15(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            pixel_channels_address0_local <= ap_const_lv64_13(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            pixel_channels_address0_local <= ap_const_lv64_11(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            pixel_channels_address0_local <= ap_const_lv64_F(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            pixel_channels_address0_local <= ap_const_lv64_D(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            pixel_channels_address0_local <= ap_const_lv64_B(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            pixel_channels_address0_local <= ap_const_lv64_9(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            pixel_channels_address0_local <= ap_const_lv64_7(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            pixel_channels_address0_local <= ap_const_lv64_5(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            pixel_channels_address0_local <= ap_const_lv64_3(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            pixel_channels_address0_local <= ap_const_lv64_1(5 - 1 downto 0);
        else 
            pixel_channels_address0_local <= "XXXXX";
        end if; 
    end process;


    pixel_channels_address1_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            pixel_channels_address1_local <= ap_const_lv64_1E(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            pixel_channels_address1_local <= ap_const_lv64_1C(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            pixel_channels_address1_local <= ap_const_lv64_1A(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            pixel_channels_address1_local <= ap_const_lv64_18(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            pixel_channels_address1_local <= ap_const_lv64_16(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            pixel_channels_address1_local <= ap_const_lv64_14(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            pixel_channels_address1_local <= ap_const_lv64_12(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            pixel_channels_address1_local <= ap_const_lv64_10(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            pixel_channels_address1_local <= ap_const_lv64_E(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            pixel_channels_address1_local <= ap_const_lv64_C(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            pixel_channels_address1_local <= ap_const_lv64_A(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            pixel_channels_address1_local <= ap_const_lv64_8(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            pixel_channels_address1_local <= ap_const_lv64_6(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            pixel_channels_address1_local <= ap_const_lv64_4(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            pixel_channels_address1_local <= ap_const_lv64_2(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            pixel_channels_address1_local <= ap_const_lv64_0(5 - 1 downto 0);
        else 
            pixel_channels_address1_local <= "XXXXX";
        end if; 
    end process;


    pixel_channels_ce0_assign_proc : process(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_ce0, ap_CS_fsm_state4, pixel_channels_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pixel_channels_ce0 <= grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_ce0;
        else 
            pixel_channels_ce0 <= pixel_channels_ce0_local;
        end if; 
    end process;


    pixel_channels_ce0_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            pixel_channels_ce0_local <= ap_const_logic_1;
        else 
            pixel_channels_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    pixel_channels_ce1_local_assign_proc : process(ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            pixel_channels_ce1_local <= ap_const_logic_1;
        else 
            pixel_channels_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    pixel_channels_we0_assign_proc : process(grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            pixel_channels_we0 <= grp_pointwise_conv_Pipeline_VITIS_LOOP_77_3_fu_414_pixel_channels_we0;
        else 
            pixel_channels_we0 <= ap_const_logic_0;
        end if; 
    end process;

    pw_weights_address0 <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address0;
    pw_weights_address1 <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_address1;
    pw_weights_ce0 <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce0;
    pw_weights_ce1 <= grp_pointwise_conv_Pipeline_VITIS_LOOP_83_4_fu_421_pw_weights_ce1;
    thr_add_fu_515_p2 <= std_logic_vector(unsigned(phi_mul390_fu_120) + unsigned(zext_ln73_fu_511_p1));
    zext_ln73_fu_511_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_403),12));
end behav;
