// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module alexnet_layer1_alexnet_layer1_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_38_2_VITIS_LOOP_39_3_VITIS_LO (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem3_0_AWVALID,
        m_axi_gmem3_0_AWREADY,
        m_axi_gmem3_0_AWADDR,
        m_axi_gmem3_0_AWID,
        m_axi_gmem3_0_AWLEN,
        m_axi_gmem3_0_AWSIZE,
        m_axi_gmem3_0_AWBURST,
        m_axi_gmem3_0_AWLOCK,
        m_axi_gmem3_0_AWCACHE,
        m_axi_gmem3_0_AWPROT,
        m_axi_gmem3_0_AWQOS,
        m_axi_gmem3_0_AWREGION,
        m_axi_gmem3_0_AWUSER,
        m_axi_gmem3_0_WVALID,
        m_axi_gmem3_0_WREADY,
        m_axi_gmem3_0_WDATA,
        m_axi_gmem3_0_WSTRB,
        m_axi_gmem3_0_WLAST,
        m_axi_gmem3_0_WID,
        m_axi_gmem3_0_WUSER,
        m_axi_gmem3_0_ARVALID,
        m_axi_gmem3_0_ARREADY,
        m_axi_gmem3_0_ARADDR,
        m_axi_gmem3_0_ARID,
        m_axi_gmem3_0_ARLEN,
        m_axi_gmem3_0_ARSIZE,
        m_axi_gmem3_0_ARBURST,
        m_axi_gmem3_0_ARLOCK,
        m_axi_gmem3_0_ARCACHE,
        m_axi_gmem3_0_ARPROT,
        m_axi_gmem3_0_ARQOS,
        m_axi_gmem3_0_ARREGION,
        m_axi_gmem3_0_ARUSER,
        m_axi_gmem3_0_RVALID,
        m_axi_gmem3_0_RREADY,
        m_axi_gmem3_0_RDATA,
        m_axi_gmem3_0_RLAST,
        m_axi_gmem3_0_RID,
        m_axi_gmem3_0_RFIFONUM,
        m_axi_gmem3_0_RUSER,
        m_axi_gmem3_0_RRESP,
        m_axi_gmem3_0_BVALID,
        m_axi_gmem3_0_BREADY,
        m_axi_gmem3_0_BRESP,
        m_axi_gmem3_0_BID,
        m_axi_gmem3_0_BUSER,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        local_weights_address0,
        local_weights_ce0,
        local_weights_we0,
        local_weights_d0,
        local_weights_1_address0,
        local_weights_1_ce0,
        local_weights_1_we0,
        local_weights_1_d0,
        local_weights_2_address0,
        local_weights_2_ce0,
        local_weights_2_we0,
        local_weights_2_d0,
        sext_ln36,
        sext_ln36_1,
        local_bias_address0,
        local_bias_ce0,
        local_bias_we0,
        local_bias_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem3_0_AWVALID;
input   m_axi_gmem3_0_AWREADY;
output  [63:0] m_axi_gmem3_0_AWADDR;
output  [0:0] m_axi_gmem3_0_AWID;
output  [31:0] m_axi_gmem3_0_AWLEN;
output  [2:0] m_axi_gmem3_0_AWSIZE;
output  [1:0] m_axi_gmem3_0_AWBURST;
output  [1:0] m_axi_gmem3_0_AWLOCK;
output  [3:0] m_axi_gmem3_0_AWCACHE;
output  [2:0] m_axi_gmem3_0_AWPROT;
output  [3:0] m_axi_gmem3_0_AWQOS;
output  [3:0] m_axi_gmem3_0_AWREGION;
output  [0:0] m_axi_gmem3_0_AWUSER;
output   m_axi_gmem3_0_WVALID;
input   m_axi_gmem3_0_WREADY;
output  [15:0] m_axi_gmem3_0_WDATA;
output  [1:0] m_axi_gmem3_0_WSTRB;
output   m_axi_gmem3_0_WLAST;
output  [0:0] m_axi_gmem3_0_WID;
output  [0:0] m_axi_gmem3_0_WUSER;
output   m_axi_gmem3_0_ARVALID;
input   m_axi_gmem3_0_ARREADY;
output  [63:0] m_axi_gmem3_0_ARADDR;
output  [0:0] m_axi_gmem3_0_ARID;
output  [31:0] m_axi_gmem3_0_ARLEN;
output  [2:0] m_axi_gmem3_0_ARSIZE;
output  [1:0] m_axi_gmem3_0_ARBURST;
output  [1:0] m_axi_gmem3_0_ARLOCK;
output  [3:0] m_axi_gmem3_0_ARCACHE;
output  [2:0] m_axi_gmem3_0_ARPROT;
output  [3:0] m_axi_gmem3_0_ARQOS;
output  [3:0] m_axi_gmem3_0_ARREGION;
output  [0:0] m_axi_gmem3_0_ARUSER;
input   m_axi_gmem3_0_RVALID;
output   m_axi_gmem3_0_RREADY;
input  [15:0] m_axi_gmem3_0_RDATA;
input   m_axi_gmem3_0_RLAST;
input  [0:0] m_axi_gmem3_0_RID;
input  [9:0] m_axi_gmem3_0_RFIFONUM;
input  [0:0] m_axi_gmem3_0_RUSER;
input  [1:0] m_axi_gmem3_0_RRESP;
input   m_axi_gmem3_0_BVALID;
output   m_axi_gmem3_0_BREADY;
input  [1:0] m_axi_gmem3_0_BRESP;
input  [0:0] m_axi_gmem3_0_BID;
input  [0:0] m_axi_gmem3_0_BUSER;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [15:0] m_axi_gmem2_0_WDATA;
output  [1:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [15:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [9:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
output  [13:0] local_weights_address0;
output   local_weights_ce0;
output   local_weights_we0;
output  [15:0] local_weights_d0;
output  [13:0] local_weights_1_address0;
output   local_weights_1_ce0;
output   local_weights_1_we0;
output  [15:0] local_weights_1_d0;
output  [13:0] local_weights_2_address0;
output   local_weights_2_ce0;
output   local_weights_2_we0;
output  [15:0] local_weights_2_d0;
input  [62:0] sext_ln36;
input  [62:0] sext_ln36_1;
output  [6:0] local_bias_address0;
output   local_bias_ce0;
output   local_bias_we0;
output  [15:0] local_bias_d0;

reg ap_idle;
reg m_axi_gmem3_0_RREADY;
reg m_axi_gmem2_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_675;
reg   [0:0] first_iter_1_mid2_reg_671;
reg   [0:0] first_iter_2_mid2_reg_658;
reg    ap_predicate_op98_read_state3;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_state4_pp0_stage0_iter3;
wire   [0:0] icmp_ln36_fu_247_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem3_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    gmem2_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] first_iter_2_mid2_fu_367_p3;
reg   [0:0] first_iter_2_mid2_reg_658_pp0_iter2_reg;
wire   [1:0] select_ln38_fu_405_p3;
reg   [1:0] select_ln38_reg_662;
reg   [1:0] select_ln38_reg_662_pp0_iter2_reg;
reg   [1:0] select_ln38_reg_662_pp0_iter3_reg;
wire   [3:0] kc_mid2_fu_431_p3;
reg   [3:0] kc_mid2_reg_666;
reg   [3:0] kc_mid2_reg_666_pp0_iter2_reg;
wire   [0:0] first_iter_1_mid2_fu_445_p3;
reg   [0:0] first_iter_1_mid2_reg_671_pp0_iter2_reg;
wire   [0:0] first_iter_0_fu_461_p2;
reg   [0:0] first_iter_0_reg_675_pp0_iter2_reg;
reg   [6:0] local_bias_addr_reg_679;
reg   [6:0] local_bias_addr_reg_679_pp0_iter2_reg;
reg   [15:0] gmem3_addr_read_reg_684;
reg   [15:0] gmem2_addr_read_reg_694;
wire   [63:0] zext_ln36_fu_467_p1;
wire   [63:0] zext_ln42_3_fu_578_p1;
reg   [3:0] kc_fu_94;
wire   [3:0] add_ln40_fu_494_p2;
wire    ap_loop_init;
reg   [3:0] kr_fu_98;
wire   [3:0] select_ln39_fu_453_p3;
reg   [7:0] indvar_flatten_fu_102;
wire   [7:0] select_ln39_1_fu_506_p3;
reg   [1:0] ic_fu_106;
reg   [8:0] indvar_flatten12_fu_110;
wire   [8:0] select_ln38_1_fu_520_p3;
reg   [6:0] oc_fu_114;
wire   [6:0] select_ln36_1_fu_339_p3;
reg   [15:0] indvar_flatten35_fu_118;
wire   [15:0] add_ln36_1_fu_253_p2;
reg    local_bias_we0_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire    ap_block_pp0_stage0_grp0;
reg    local_bias_ce0_local;
reg    local_weights_1_we0_local;
reg    local_weights_1_ce0_local;
reg    local_weights_we0_local;
reg    local_weights_ce0_local;
reg    local_weights_2_we0_local;
reg    local_weights_2_ce0_local;
wire   [0:0] icmp_ln38_fu_277_p2;
wire   [0:0] first_iter_269_fu_291_p2;
wire   [0:0] first_iter_172_fu_303_p2;
wire   [0:0] icmp_ln39_fu_327_p2;
wire   [0:0] xor_ln36_fu_315_p2;
wire   [6:0] add_ln36_fu_271_p2;
wire   [1:0] select_ln36_fu_283_p3;
wire   [0:0] and_ln36_1_fu_333_p2;
wire   [0:0] empty_123_fu_353_p2;
wire   [0:0] or_ln36_fu_297_p2;
wire   [0:0] or_ln36_1_fu_309_p2;
wire   [0:0] exitcond_flatten_not_fu_381_p2;
wire   [0:0] not_exitcond_flatten_mid234_fu_387_p2;
wire   [0:0] and_ln36_fu_393_p2;
wire   [0:0] icmp_ln40_fu_321_p2;
wire   [1:0] add_ln38_fu_347_p2;
wire   [3:0] kr_mid26_fu_359_p3;
wire   [0:0] icmp_ln40_mid211_fu_399_p2;
wire   [0:0] empty_124_fu_419_p2;
wire   [0:0] empty_125_fu_425_p2;
wire   [3:0] add_ln39_fu_413_p2;
wire   [0:0] first_iter_1_mid1_fu_439_p2;
wire   [0:0] first_iter_1_mid29_fu_375_p2;
wire   [6:0] mul_ln42_fu_476_p0;
wire   [4:0] mul_ln42_fu_476_p1;
wire   [7:0] add_ln39_1_fu_500_p2;
wire   [8:0] add_ln38_1_fu_514_p2;
wire   [13:0] grp_fu_584_p4;
wire   [10:0] mul_ln42_fu_476_p2;
wire   [3:0] grp_fu_584_p1;
wire   [3:0] grp_fu_584_p2;
wire   [3:0] grp_fu_584_p3;
reg    grp_fu_584_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [10:0] grp_fu_584_p10;
wire   [13:0] grp_fu_584_p30;
wire   [10:0] mul_ln42_fu_476_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 kc_fu_94 = 4'd0;
#0 kr_fu_98 = 4'd0;
#0 indvar_flatten_fu_102 = 8'd0;
#0 ic_fu_106 = 2'd0;
#0 indvar_flatten12_fu_110 = 9'd0;
#0 oc_fu_114 = 7'd0;
#0 indvar_flatten35_fu_118 = 16'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

alexnet_layer1_mul_7ns_5ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 11 ))
mul_7ns_5ns_11_1_1_U1(
    .din0(mul_ln42_fu_476_p0),
    .din1(mul_ln42_fu_476_p1),
    .dout(mul_ln42_fu_476_p2)
);

alexnet_layer1_ama_addmuladd_11ns_4ns_4ns_4ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .dout_WIDTH( 14 ))
ama_addmuladd_11ns_4ns_4ns_4ns_14_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln42_fu_476_p2),
    .din1(grp_fu_584_p1),
    .din2(grp_fu_584_p2),
    .din3(grp_fu_584_p3),
    .ce(grp_fu_584_ce),
    .dout(grp_fu_584_p4)
);

alexnet_layer1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            ic_fu_106 <= 2'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_247_p2 == 1'd0))) begin
            ic_fu_106 <= select_ln38_fu_405_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_110 <= 9'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_247_p2 == 1'd0))) begin
            indvar_flatten12_fu_110 <= select_ln38_1_fu_520_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten35_fu_118 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_247_p2 == 1'd0))) begin
            indvar_flatten35_fu_118 <= add_ln36_1_fu_253_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_102 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_247_p2 == 1'd0))) begin
            indvar_flatten_fu_102 <= select_ln39_1_fu_506_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            kc_fu_94 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_247_p2 == 1'd0))) begin
            kc_fu_94 <= add_ln40_fu_494_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            kr_fu_98 <= 4'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_247_p2 == 1'd0))) begin
            kr_fu_98 <= select_ln39_fu_453_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            oc_fu_114 <= 7'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln36_fu_247_p2 == 1'd0))) begin
            oc_fu_114 <= select_ln36_1_fu_339_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        first_iter_0_reg_675 <= first_iter_0_fu_461_p2;
        first_iter_1_mid2_reg_671 <= first_iter_1_mid2_fu_445_p3;
        first_iter_2_mid2_reg_658 <= first_iter_2_mid2_fu_367_p3;
        kc_mid2_reg_666 <= kc_mid2_fu_431_p3;
        local_bias_addr_reg_679 <= zext_ln36_fu_467_p1;
        select_ln38_reg_662 <= select_ln38_fu_405_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        first_iter_0_reg_675_pp0_iter2_reg <= first_iter_0_reg_675;
        first_iter_1_mid2_reg_671_pp0_iter2_reg <= first_iter_1_mid2_reg_671;
        first_iter_2_mid2_reg_658_pp0_iter2_reg <= first_iter_2_mid2_reg_658;
        gmem2_addr_read_reg_694 <= m_axi_gmem2_0_RDATA;
        kc_mid2_reg_666_pp0_iter2_reg <= kc_mid2_reg_666;
        local_bias_addr_reg_679_pp0_iter2_reg <= local_bias_addr_reg_679;
        select_ln38_reg_662_pp0_iter2_reg <= select_ln38_reg_662;
        select_ln38_reg_662_pp0_iter3_reg <= select_ln38_reg_662_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg))) begin
        gmem3_addr_read_reg_684 <= m_axi_gmem3_0_RDATA;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln36_fu_247_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem2_blk_n_R = m_axi_gmem2_0_RVALID;
    end else begin
        gmem2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_predicate_op98_read_state3 == 1'b1))) begin
        gmem3_blk_n_R = m_axi_gmem3_0_RVALID;
    end else begin
        gmem3_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_584_ce = 1'b1;
    end else begin
        grp_fu_584_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_bias_ce0_local = 1'b1;
    end else begin
        local_bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((first_iter_0_reg_675_pp0_iter2_reg == 1'd1) & (first_iter_1_mid2_reg_671_pp0_iter2_reg == 1'd1) & (first_iter_2_mid2_reg_658_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        local_bias_we0_local = 1'b1;
    end else begin
        local_bias_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_weights_1_ce0_local = 1'b1;
    end else begin
        local_weights_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln38_reg_662_pp0_iter3_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_weights_1_we0_local = 1'b1;
    end else begin
        local_weights_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_weights_2_ce0_local = 1'b1;
    end else begin
        local_weights_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln38_reg_662_pp0_iter3_reg == 2'd0) & ~(select_ln38_reg_662_pp0_iter3_reg == 2'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_weights_2_we0_local = 1'b1;
    end else begin
        local_weights_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_weights_ce0_local = 1'b1;
    end else begin
        local_weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (select_ln38_reg_662_pp0_iter3_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        local_weights_we0_local = 1'b1;
    end else begin
        local_weights_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem2_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_predicate_op98_read_state3 == 1'b1))) begin
        m_axi_gmem3_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem3_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_1_fu_253_p2 = (indvar_flatten35_fu_118 + 16'd1);

assign add_ln36_fu_271_p2 = (oc_fu_114 + 7'd1);

assign add_ln38_1_fu_514_p2 = (indvar_flatten12_fu_110 + 9'd1);

assign add_ln38_fu_347_p2 = (select_ln36_fu_283_p3 + 2'd1);

assign add_ln39_1_fu_500_p2 = (indvar_flatten_fu_102 + 8'd1);

assign add_ln39_fu_413_p2 = (kr_mid26_fu_359_p3 + 4'd1);

assign add_ln40_fu_494_p2 = (kc_mid2_fu_431_p3 + 4'd1);

assign and_ln36_1_fu_333_p2 = (xor_ln36_fu_315_p2 & icmp_ln39_fu_327_p2);

assign and_ln36_fu_393_p2 = (xor_ln36_fu_315_p2 & not_exitcond_flatten_mid234_fu_387_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((m_axi_gmem3_0_RVALID == 1'b0) & (ap_predicate_op98_read_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (m_axi_gmem2_0_RVALID == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

always @ (*) begin
    ap_predicate_op98_read_state3 = ((first_iter_2_mid2_reg_658 == 1'd1) & (first_iter_1_mid2_reg_671 == 1'd1) & (first_iter_0_reg_675 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign empty_123_fu_353_p2 = (icmp_ln38_fu_277_p2 | and_ln36_1_fu_333_p2);

assign empty_124_fu_419_p2 = (icmp_ln40_mid211_fu_399_p2 | and_ln36_1_fu_333_p2);

assign empty_125_fu_425_p2 = (icmp_ln38_fu_277_p2 | empty_124_fu_419_p2);

assign exitcond_flatten_not_fu_381_p2 = (icmp_ln39_fu_327_p2 ^ 1'd1);

assign first_iter_0_fu_461_p2 = ((kc_mid2_fu_431_p3 == 4'd0) ? 1'b1 : 1'b0);

assign first_iter_172_fu_303_p2 = ((kr_fu_98 == 4'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid1_fu_439_p2 = ((add_ln39_fu_413_p2 == 4'd0) ? 1'b1 : 1'b0);

assign first_iter_1_mid29_fu_375_p2 = (or_ln36_1_fu_309_p2 | and_ln36_1_fu_333_p2);

assign first_iter_1_mid2_fu_445_p3 = ((icmp_ln40_mid211_fu_399_p2[0:0] == 1'b1) ? first_iter_1_mid1_fu_439_p2 : first_iter_1_mid29_fu_375_p2);

assign first_iter_269_fu_291_p2 = ((ic_fu_106 == 2'd0) ? 1'b1 : 1'b0);

assign first_iter_2_mid2_fu_367_p3 = ((and_ln36_1_fu_333_p2[0:0] == 1'b1) ? 1'd0 : or_ln36_fu_297_p2);

assign grp_fu_584_p1 = grp_fu_584_p10;

assign grp_fu_584_p10 = select_ln39_fu_453_p3;

assign grp_fu_584_p2 = 14'd11;

assign grp_fu_584_p3 = grp_fu_584_p30;

assign grp_fu_584_p30 = kc_mid2_reg_666_pp0_iter2_reg;

assign icmp_ln36_fu_247_p2 = ((indvar_flatten35_fu_118 == 16'd34848) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_277_p2 = ((indvar_flatten12_fu_110 == 9'd363) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_327_p2 = ((indvar_flatten_fu_102 == 8'd121) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_321_p2 = ((kc_fu_94 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln40_mid211_fu_399_p2 = (icmp_ln40_fu_321_p2 & and_ln36_fu_393_p2);

assign kc_mid2_fu_431_p3 = ((empty_125_fu_425_p2[0:0] == 1'b1) ? 4'd0 : kc_fu_94);

assign kr_mid26_fu_359_p3 = ((empty_123_fu_353_p2[0:0] == 1'b1) ? 4'd0 : kr_fu_98);

assign local_bias_address0 = local_bias_addr_reg_679_pp0_iter2_reg;

assign local_bias_ce0 = local_bias_ce0_local;

assign local_bias_d0 = gmem3_addr_read_reg_684;

assign local_bias_we0 = local_bias_we0_local;

assign local_weights_1_address0 = zext_ln42_3_fu_578_p1;

assign local_weights_1_ce0 = local_weights_1_ce0_local;

assign local_weights_1_d0 = gmem2_addr_read_reg_694;

assign local_weights_1_we0 = local_weights_1_we0_local;

assign local_weights_2_address0 = zext_ln42_3_fu_578_p1;

assign local_weights_2_ce0 = local_weights_2_ce0_local;

assign local_weights_2_d0 = gmem2_addr_read_reg_694;

assign local_weights_2_we0 = local_weights_2_we0_local;

assign local_weights_address0 = zext_ln42_3_fu_578_p1;

assign local_weights_ce0 = local_weights_ce0_local;

assign local_weights_d0 = gmem2_addr_read_reg_694;

assign local_weights_we0 = local_weights_we0_local;

assign m_axi_gmem2_0_ARADDR = 64'd0;

assign m_axi_gmem2_0_ARBURST = 2'd0;

assign m_axi_gmem2_0_ARCACHE = 4'd0;

assign m_axi_gmem2_0_ARID = 1'd0;

assign m_axi_gmem2_0_ARLEN = 32'd0;

assign m_axi_gmem2_0_ARLOCK = 2'd0;

assign m_axi_gmem2_0_ARPROT = 3'd0;

assign m_axi_gmem2_0_ARQOS = 4'd0;

assign m_axi_gmem2_0_ARREGION = 4'd0;

assign m_axi_gmem2_0_ARSIZE = 3'd0;

assign m_axi_gmem2_0_ARUSER = 1'd0;

assign m_axi_gmem2_0_ARVALID = 1'b0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = 16'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 2'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign m_axi_gmem3_0_ARADDR = 64'd0;

assign m_axi_gmem3_0_ARBURST = 2'd0;

assign m_axi_gmem3_0_ARCACHE = 4'd0;

assign m_axi_gmem3_0_ARID = 1'd0;

assign m_axi_gmem3_0_ARLEN = 32'd0;

assign m_axi_gmem3_0_ARLOCK = 2'd0;

assign m_axi_gmem3_0_ARPROT = 3'd0;

assign m_axi_gmem3_0_ARQOS = 4'd0;

assign m_axi_gmem3_0_ARREGION = 4'd0;

assign m_axi_gmem3_0_ARSIZE = 3'd0;

assign m_axi_gmem3_0_ARUSER = 1'd0;

assign m_axi_gmem3_0_ARVALID = 1'b0;

assign m_axi_gmem3_0_AWADDR = 64'd0;

assign m_axi_gmem3_0_AWBURST = 2'd0;

assign m_axi_gmem3_0_AWCACHE = 4'd0;

assign m_axi_gmem3_0_AWID = 1'd0;

assign m_axi_gmem3_0_AWLEN = 32'd0;

assign m_axi_gmem3_0_AWLOCK = 2'd0;

assign m_axi_gmem3_0_AWPROT = 3'd0;

assign m_axi_gmem3_0_AWQOS = 4'd0;

assign m_axi_gmem3_0_AWREGION = 4'd0;

assign m_axi_gmem3_0_AWSIZE = 3'd0;

assign m_axi_gmem3_0_AWUSER = 1'd0;

assign m_axi_gmem3_0_AWVALID = 1'b0;

assign m_axi_gmem3_0_BREADY = 1'b0;

assign m_axi_gmem3_0_WDATA = 16'd0;

assign m_axi_gmem3_0_WID = 1'd0;

assign m_axi_gmem3_0_WLAST = 1'b0;

assign m_axi_gmem3_0_WSTRB = 2'd0;

assign m_axi_gmem3_0_WUSER = 1'd0;

assign m_axi_gmem3_0_WVALID = 1'b0;

assign mul_ln42_fu_476_p0 = mul_ln42_fu_476_p00;

assign mul_ln42_fu_476_p00 = select_ln36_1_fu_339_p3;

assign mul_ln42_fu_476_p1 = 11'd11;

assign not_exitcond_flatten_mid234_fu_387_p2 = (icmp_ln38_fu_277_p2 | exitcond_flatten_not_fu_381_p2);

assign or_ln36_1_fu_309_p2 = (icmp_ln38_fu_277_p2 | first_iter_172_fu_303_p2);

assign or_ln36_fu_297_p2 = (icmp_ln38_fu_277_p2 | first_iter_269_fu_291_p2);

assign select_ln36_1_fu_339_p3 = ((icmp_ln38_fu_277_p2[0:0] == 1'b1) ? add_ln36_fu_271_p2 : oc_fu_114);

assign select_ln36_fu_283_p3 = ((icmp_ln38_fu_277_p2[0:0] == 1'b1) ? 2'd0 : ic_fu_106);

assign select_ln38_1_fu_520_p3 = ((icmp_ln38_fu_277_p2[0:0] == 1'b1) ? 9'd1 : add_ln38_1_fu_514_p2);

assign select_ln38_fu_405_p3 = ((and_ln36_1_fu_333_p2[0:0] == 1'b1) ? add_ln38_fu_347_p2 : select_ln36_fu_283_p3);

assign select_ln39_1_fu_506_p3 = ((empty_123_fu_353_p2[0:0] == 1'b1) ? 8'd1 : add_ln39_1_fu_500_p2);

assign select_ln39_fu_453_p3 = ((icmp_ln40_mid211_fu_399_p2[0:0] == 1'b1) ? add_ln39_fu_413_p2 : kr_mid26_fu_359_p3);

assign xor_ln36_fu_315_p2 = (icmp_ln38_fu_277_p2 ^ 1'd1);

assign zext_ln36_fu_467_p1 = select_ln36_1_fu_339_p3;

assign zext_ln42_3_fu_578_p1 = grp_fu_584_p4;

endmodule //alexnet_layer1_alexnet_layer1_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_38_2_VITIS_LOOP_39_3_VITIS_LO
